# Generated by Django 4.2.13 on 2024-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StyleTrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PicTest',
        ),
    ]
